version: "3"
services:
  mysql:
    image: mysql:8.0.18
    container_name: wts_mysql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
    ]
    restart: always
    # ports:
    # - "3306:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
  server:
    image: wts_server:latest
    container_name: wts_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  nginx:
    image: wts_nginx:latest
    container_name: wts_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - server